spring.profiles.include=tms

spring.datasource.url=jdbc:postgresql://db:5432/tms
spring.datasource.username=postgres
spring.datasource.password=pingan
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP configuration
spring.datasource.hikari.max-wait=30000
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-test-query=select 1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.initialization-fail-timeout=1
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.leak-detection-threshold=60000

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

#logging.level.com.lhjz.portal=INFO
logging.file.path=log/tms
logging.file.name=tms.log

spring.messages.basename=messages,views
spring.messages.encoding=ISO-8859-1

spring.thymeleaf.cache=true
spring.thymeleaf.mode=HTML

server.port=8085
server.servlet.context-path=
#server.session.timeout=86400

management.endpoints.web.base-path=/manage

tms.blog.md2pdf.path=/home/tms/md2pdf

