

spring.datasource.url=jdbc:mysql://localhost:3306/tms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=pingan
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP configuration
spring.datasource.hikari.max-wait=30000
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-test-query=select 1 from dual
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.initialization-fail-timeout=1
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.leak-detection-threshold=60000

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=none
# 显示生成的 SQL
#spring.jpa.show-sql=true
# 格式化 SQL 输出
#spring.jpa.properties.hibernate.format_sql=true
# 打印参数
#logging.level.org.hibernate.type=TRACE

#logging.level.com.lhjz.portal=DEBUG
#logging.level.com.lhjz.portal=INFO
logging.file.path=log/tms
logging.file.name=tms.log

spring.messages.basename=messages,views
spring.messages.encoding=ISO-8859-1

spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

server.port=8080
server.servlet.context-path=

management.endpoints.web.base-path=/manage

tms.blog.md2pdf.path=/Users/xiweicheng/md2pdf

# 设置单个文件的最大大小为50MB
spring.servlet.multipart.max-file-size=50MB
# 设置整个请求的最大大小为50MB
spring.servlet.multipart.max-request-size=50MB
# 配置Tomcat连接器的最大POST大小
server.tomcat.max-http-post-size=104857600
