package com.lhjz.portal.entity.security;
// default package
// Generated May 6, 2015 11:39:38 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupAuthorityId generated by hbm2java
 */
@Embeddable
public class GroupAuthorityId implements java.io.Serializable {

	/** serialVersionUID long */
	private static final long serialVersionUID = -7564608728716685119L;
	private long groupId;
	private String authority;

	public GroupAuthorityId() {
	}

	public GroupAuthorityId(long groupId, String authority) {
		this.groupId = groupId;
		this.authority = authority;
	}

	@Column(name = "group_id", nullable = false)
	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	@Column(name = "authority", nullable = false, length = 50)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@Override
    public boolean equals(Object other) {
		if ((this == other)) {
            return true;
        }
		if ((other == null)) {
            return false;
        }
		if (!(other instanceof GroupAuthorityId)) {
            return false;
        }
		GroupAuthorityId castOther = (GroupAuthorityId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& ((this.getAuthority() == castOther.getAuthority()) || (this.getAuthority() != null
						&& castOther.getAuthority() != null && this.getAuthority().equals(castOther.getAuthority())));
	}

	@Override
    public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getGroupId();
		result = 37 * result + (getAuthority() == null ? 0 : this.getAuthority().hashCode());
		return result;
	}

}
